services:
  cvmaker:
    image: cvmaker  
    ports:
      - "3000:3000"
    command: ["sh", "-c", "node index"] 
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cvmaker
    ports:
      - "3303:3306"
    
    restart: always # restart the container if it stops because of an error (like db not ready)
    
